# This will enforce that ONLY traffic that is TLS is allowed between proxies
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "default"
spec:
  mtls:
    mode: STRICT
---
# # Switch mtls between proxies
# apiVersion: "networking.istio.io/v1alpha3"
# kind: "DestinationRule"
# metadata:
#   name: "default"
# spec:
#   host: "*.local" # Every SINGLE SERVICE 
#   trafficPolicy:
#     tls:
#       mode: ISTIO_MUTUAL
---
# Hydra Oauth2 
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: hydra-service
spec:
  selector:
    matchLabels:
      service: hydra
  mtls:
    mode: PERMISSIVE
  # portLevelMtls:
  #   443:
  #     mode: PERMISSIVE
---
# Gateway Service   
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway
  mtls:
    mode: PERMISSIVE
  # portLevelMtls:
  #   443:
  #     mode: PERMISSIVE
---
# Gateway Service   
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: oauth-service
spec:
  selector:
    matchLabels:
      app: oauth-front
  mtls:
    mode: PERMISSIVE
  # portLevelMtls:
  #   443:
  #     mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-to-k8s
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE